questions = {
    "We would like to welcome you": "HELLO",
    "Delicate sun & moon": "HELLO",
    "Hwasahan, Myunbyeori, Solla & Wiin": "HELLO",
    "Go go go like this": "BATON TOUCH",
    "Hello, Ladies and gentleman, So beautiful": "BATON TOUCH",
    "Sinnage nolja Dance With Me": "BATON TOUCH",
    "Are you ready for perfection": "PIANO MAN",
    " Bumppappara bumppappara bumppappara bum": "PIANO MAN",
    "Nameullae ireoke": "PIANO MAN",
    "Yeojayeosseo? OH MY GOD!": "UM OH AH YEH",
    "Tteugeowojineun i bunwigi": "UM OH AH YEH",
    "Oh yes eum o a ye": "UM OH AH YEH",
    "Come on Hey Sister": "YOU'RE THE BEST",
    "Hey Mr saenggagi meotjin namja baro neo": "YOU'RE THE BEST",
    "I like eye contact": "YOU'RE THE BEST",
    "Nan neoneoneoneoneo": "I MISS YOU",
    "So much I miss you": "I MISS YOU",
    "Joheun noraessoriga deullimyeon": "I MISS YOU",
    "Neowana ipeul majchweo I feel good": "DECALCOMANIE",
    "Jogeumeun wiheomhae wiheomhae wiheomhaedo": "DECALCOMANIE",
    "Du soneul meoriwiro clap your hands": "DECALCOMANIE",
    "I can't control my mind": "MY STAR",
    "You are my shining star": "MY STAR",
    "Let's walk up the night sky": "MY STAR"
}
