questions = {
    "We would like to welcome you": "HELLO",
    "Delicate sun & moon": "HELLO",
    "Hwasahan, Myunbyeori, Solla & Wiin": "HELLO",
    "Go go go like this": "BATON TOUCH",
    "Hello, Ladies and gentleman, So beautiful": "BATON TOUCH",
    "Sinnage nolja Dance With Me": "BATON TOUCH",
    "Are you ready for perfection": "PIANO MAN",
    "Bumppappara bumppappara bumppappara bum": "PIANO MAN",
    "Nameullae ireoke": "PIANO MAN",
    "Yeojayeosseo? OH MY GOD!": "UM OH AH YEH",
    "Tteugeowojineun i bunwigi": "UM OH AH YEH",
    "Oh yes eum o a ye": "UM OH AH YEH",
    "Come on Hey Sister": "YOU'RE THE BEST",
    "Hey Mr saenggagi meotjin namja baro neo": "YOU'RE THE BEST",
    "I like eye contact": "YOU'RE THE BEST",
    "Nan neoneoneoneoneo": "I MISS YOU",
    "So much I miss you": "I MISS YOU",
    "Joheun noraessoriga deullimyeon": "I MISS YOU",
    "Neowana ipeul majchweo I feel good": "DECALCOMANIE",
    "Jogeumeun wiheomhae wiheomhae wiheomhaedo": "DECALCOMANIE",
    "Du soneul meoriwiro clap your hands": "DECALCOMANIE",
    "I can't control my mind": "MY STAR",
    "You are my shining star": "MY STAR",
    "Let's walk up the night sky": "MY STAR",
    "Iboda joeul su isseukka": "I LOVE TOO",
    "oreul bomyeo hamkke unneun na": "I LOVE TOO",
    "Shigan jinamyeon iksukhame Soholhaejineun mam": "I LOVE TOO",
    "Ppeonhadippeonhan nae sarang iyagiya": "WIND FLOWER",
    "Get better day by day": "WIND FLOWER",
    "Wind flower, wi-wind flower": "WIND FLOWER",
    "Neo bodan neo bodan naega deo keo": "TALLER THAN YOU",
    "Mamamoo mamamoo mamamoo": "TALLER THAN YOU",
    "Uri kkirikkirikkiri ttak ilsenchi chai": "TALLER THAN YOU",
    "Me me 4 with Sun": "YES I AM",
    "Hello bonjour nǐhǎo annyeong": "YES I AM",
    "Dwittarawa dwittarawa, Follow me-e ay ay": "YES I AM",
    "Dal-i dal-i balg-awa, Bich-eul geuligo iss-eo": "STARRY NIGHT",
    "Yayayayaiya": "STARRY NIGHT",
    "Nega hwihwihwi bul-eowa": "STARRY NIGHT",
    "All I wanna be is meotjim Nae maeumdaero golla kick it": "HIP",
    "Geunde waeirae ne eolgure chim baenni (kaktu)": "HIP",
    "Jakku click me click me Hollin deusi zoom Close up close up close up": "HIP",
    "Drink like a like a like a fish": "DINGGA",
    "1, 2, 3, 4 ne apeul bwa Wae dadeul hwana isseo": "DINGGA",
    "I need to love myself All I need is your heart, Oh me oh my ay": "DINGGA",
    "I wanna be free Just gonna be free": "SELFISH",
    "Sometime being selfish Ohae mal-a nappeun uimineun anya": "SELFISH",
    "Jogeum deo soljighaejilge I love myself": "SELFISH",
    "Areumdaun i byeol Igose neowa gateun kkumeul kkudeon uri dul": "WHERE ARE WE NOW",
    " On and on We're on the road": "WHERE ARE WE NOW",
    "Talking about where we goin\'": "WHERE ARE WE NOW",
}
